# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum11_uyg5/prj_bolum11_uyg5.srcs/sources_1/ip/Floating_KUCUK/Floating_KUCUK.xci
# IP: The module: 'Floating_KUCUK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum11_uyg5/prj_bolum11_uyg5.srcs/sources_1/ip/Floating_KUCUK/Floating_KUCUK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Floating_KUCUK'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum11_uyg5/prj_bolum11_uyg5.srcs/sources_1/ip/Floating_KUCUK/Floating_KUCUK.xci
# IP: The module: 'Floating_KUCUK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum11_uyg5/prj_bolum11_uyg5.srcs/sources_1/ip/Floating_KUCUK/Floating_KUCUK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Floating_KUCUK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
