webtalk_init -webtalk_dir E:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum3_uyg1/prj_bolum3_uyg1.sim/sim_1/behav/xsim/xsim.dir/Uyg01_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul  2 21:14:36 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "deab8a99-6bb2-44f3-99c9-0fcd99abf4c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "662ea4e0d9cc4ac4ab695a3dd6a96109" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "201 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8688_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3811127229 -regid "" -xml E:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum3_uyg1/prj_bolum3_uyg1.sim/sim_1/behav/xsim/xsim.dir/Uyg01_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum3_uyg1/prj_bolum3_uyg1.sim/sim_1/behav/xsim/xsim.dir/Uyg01_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/bildiri ve makaleler/kitap/fpga/uygulamalar/prj_bolum3_uyg1/prj_bolum3_uyg1.sim/sim_1/behav/xsim/xsim.dir/Uyg01_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
